name = "newsletter-worker"
type = "javascript"

# Define the Durable Object binding
[[durable_objects]]
name = "SUBSCRIBER_STORE"
class_name = "SubscriberStore"

[[bindings]]
type = "durable_object_namespace"
name = "SUBSCRIBER_STORE"
class_name = "SubscriberStore"

# Your Cloudflare account ID
account_id = "your_account_id"
workers_dev = true
compatibility_date = "2024-01-01"
